# Generated by Django 4.2.1 on 2023-05-17 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_cart_product_tags_alter_product_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-rate']},
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.AlterField(
            model_name='product',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
