# Generated by Django 4.2.1 on 2023-05-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_cart_status_blacklistedtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Ordered', 'Ordered'), ('On the way', 'On the way'), ('Rejected', 'Rejected'), ('Received', 'Received'), ('Delivered', 'Delivered'), ('Approved', 'Approved')], default='Draft', max_length=10),
        ),
    ]
