# Generated by Django 4.2.1 on 2023-07-06 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_msg_file_alter_msg_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msg',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='chat/files/'),
        ),
        migrations.AlterField(
            model_name='msg',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='chat/images/'),
        ),
    ]
